version: "2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.5
    container_name: elasticsearch-datcn
    environment:
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - "discovery.type=single-node"
     - xpack.monitoring.collection.enabled=true
     - cluster.routing.allocation.disk.threshold_enabled=false
     - xpack.security.enabled=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9202:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.5
    container_name: kibana-datcn
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch-datcn:9200"
      - xpack.security.enabled=false
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearch
      
volumes:
  elasticsearch_data:
    driver: local

